### ISSUE TITLE
Apidog

### ISSUE THREAD

**Issue by YukioIkeda** [OAI/Tooling#107]
> **Please use this template for tools that cannot be tagged on GitHub. If your tool is on GitHub use the `openapi3` and `openapi31` tags to allow your data to be collected automatically.**

## Tool Properties

> **Please replace all placeholders marked in bold in the bullets below with the requested information. Use plain text for your information.**

- Display name: **Apidog**
- Description: **Apidog is an integrated collaboration platform for API documentation, API debugging, API mocking, and API automated testing that combines Postman + Swagger + Mock + JMeter to tackle the data synchronization problem among different systems using a set of systems and a set of data. API debugging, API data mocking, and API automated testing can be directly used without redefining as long as the API documentation is well-defined.**
- Homepage: https://www.apidog.com

## OpenAPI Versions

> **Please indicate the versions of OpenAPI supported by your tool by marking them true or false below.**

- 3.1: true
- 3.0: true
- 2.0: true

**Comment by SensibleWood** [comment]
@YukioIkeda I made some changes to ensure this will be automatically consumed at the next full build and also added https:// to your URL in the ticket.

This will be ingested in the next full build at the weekend.

**Comment by SensibleWood** [comment]
@YukioIkeda its now in the list:

<img width="1904" alt="image" src="https://github.com/OAI/Tooling/assets/2420069/d3f7edfb-812a-4d35-bc9a-8fdc465e6e9f">

Closing the ticket.

**Comment by gaston-haro** [comment]
@YukioIkeda why does apidog.com say it is open source and you don't provide any public repos? Stop scamming people
