### ISSUE TITLE
Project has correct tags but is unlisted

### ISSUE THREAD

**Issue by AndrewWalsh** [OAI/Tooling#108]
> **Please use this template for tools that cannot be tagged on GitHub. If your tool is on GitHub use the `openapi3` and `openapi31` tags to allow your data to be collected automatically.**

Hi there, I have a project below that has the correct topic tags but is unlisted. Would it be possible to list this under `Auto Generators`?

> **Please replace all placeholders marked in bold in the bullets below with the requested information. Use plain text for your information.**

- Display name: OpenAPI DevTools
- Description: Chrome extension that generates API specs for any app or website
- Repository: https://github.com/AndrewWalsh/openapi-devtools
- Homepage: https://chromewebstore.google.com/detail/openapi-devtools/jelghndoknklgabjgaeppjhommkkmdii

## OpenAPI Versions

> **Please indicate the versions of OpenAPI supported by your tool by marking them true or false below.**

- 3.1: true
- 3.0: true
- 2.0: false

**Comment by SensibleWood** [comment]
Hello @AndrewWalsh thanks for raising this. I'll take a look at why we aren't seeing your data in the GraphQL query from GitHub, but this'll get pulled in when the full build runs at the weekend

**Comment by AndrewWalsh** [comment]
Thanks @SensibleWood. Took a look today and can see it on https://tools.openapis.org/, but it hasn't been categorised correctly. Would it be possible to put this under `Auto Generators`?

**Comment by SensibleWood** [comment]
@AndrewWalsh thanks for confirming. There was actually some outstanding work to do to manually set the category as I left it to the Bayesian analysis thing the build runs. I've opened a branch against this issue and will work on the change in the next day or so

**Comment by AndrewWalsh** [comment]
Awesome thank you @SensibleWood

**Comment by SensibleWood** [comment]
Hi @AndrewWalsh sorry this took so long to sort out but other stuff got in the way. Anyhoo:

![image](https://github.com/OAI/Tooling/assets/2420069/876b9367-dca2-45f2-bc1b-dbfa12d7f564)

👍 closing this puppy down now
