### ISSUE TITLE
Xapi Platform

### ISSUE THREAD

**Issue by KalanaRavishanka** [OAI/Tooling#109]
## Tool Properties

- Display name: **Xapi Platform**
- Description: **Xapi is an integrated platform that enables you to implement a streamlined API-first design strategy with standardized API artifacts and collaborative teams.**
- Repository: -
- Homepage: **https://xapihub.io/**

## OpenAPI Versions

- 3.1: true
- 3.0: false
- 2.0: false

**Comment by SensibleWood** [comment]
This was successfully added to the repository so closing (should have auto-closed, but appears to a bug...)
