### ISSUE TITLE
Adding Frogment GUI editor

### ISSUE THREAD

**Issue by rajnandan1** [OAI/Tooling#115]
## Tool Properties

- Display name: Frogment
- Description: A free openAPI spec editor and linter that breaks down your spec into fragments to make editing easier and more intuitive.
- Homepage: https://www.frogment.com/

## OpenAPI Versions

- 3.1: true
- 3.0: true
- 2.0: true

**Comment by SensibleWood** [comment]
@rajnandan1 This data was added to our repository. However its already present on data retrieved from https://openapi.tools so I'm going to back it out as it's current duplicated:

![image](https://github.com/OAI/Tooling/assets/2420069/eba61c48-7630-4c40-a1f8-f5d56cdad8c9)
