### ISSUE TITLE
Data fixes for duplicate data

### ISSUE THREAD

**Issue by SensibleWood** [OAI/Tooling#53]
**Describe the bug**

There are duplicates on the website under the Parsers section:

![image](https://user-images.githubusercontent.com/2420069/174331646-76da18c7-36e2-49ca-af49-a8a7f61ddfa9.png)

**To Reproduce**

* Go to [homepage](https://oai.github.io/Tooling)
* Click [Parsers](https://oai.github.io/Tooling/categories/parsers.html)
* Order by Stars and there it is.

**Expected behavior**

Should be no duplicates.

**Additional context**

* Need to revisit data collection approach and see how such entries should be merged.
* Script and run a data fix to merge.

**Comment by philsturgeon** [comment]
I've been playing around with this for a while and it looks like that repo has been moved to an org. The API will still take the URL and respond with the same repo metadata, but if you add 

````
   const paths = [
+    { source: '$.data.html_url', target: 'guid' },
```

I think we can use the HTML URL as the globally unique ID in order to eject the one which doesn't match the organization/repo (could be various old redirects, so eject any that dont match).

**Comment by SensibleWood** [comment]
Summary of the work done for this issue:

* Ensure that in all cases a **lowercase** repository URL is used for consistent matching. URLs need to be cleaned up further (but that is beyond the scope of this work).
* Build now implements several new behaviours:
  * Checks GitHub for a `301`: If `301` is returned then mark repository as moved. Use the returned `url` value to resolve the `html_url` value from GitHub.
  * If metadata is already available for the moved repository then the data is discard. The target repository is updated with an array called `oldLocations` that contains the old URL.
  * If there is no metadata for the target repository then the `repository` property is updated to the new `url` and the `oldLocations` array added.
  * On the next build `oldLocations` is then used to ignore any repositories pulled in from sources that have been moved.
  * Dead repositories are removed i.e. 404, no redirect.
* Other incidental stuff:
  * CNAME rewritten as part of `build:site`.
  * Spelling correction in `index.njk`.

Note that **there are still duplicates** but they are far fewer. The matching needs to be revisited to deal with this.
