### ISSUE TITLE
Add @himenon/openapi-typescript-code-generator

### ISSUE THREAD

**Issue by Himenon** [OAI/Tooling#73]
## Tool Properties

- Display name: @himenon/openapi-typescript-code-generator
- Description: TypeScript code generator via OpenAPI scheme.
- Repository: https://github.com/Himenon/openapi-typescript-code-generator
- Homepage: 

## OpenAPI Versions

- 3.1: false
- 3.0: true
- 2.0: false

**Comment by SensibleWood** [comment]
Howdy @Himenon your repository are already in the tooling repository under the "SDK" category:

![image](https://github.com/OAI/Tooling/assets/2420069/f4fc91d7-4f78-4e3d-94e9-a432f46e9bc2)

Your metadata was collected through the `openapi3` topic on your repository. Closing this ticket.
