### ISSUE TITLE
Update openapi json schema generator

### ISSUE THREAD

**Issue by spacether** [OAI/Tooling#96]
## User Story

Update openapi json schema generator

## Detailed Requirement

Now fill in the blanks:

* How would this work?
3.1 document processing now works, this needs to be added
* What's the approach to implementing it?
* Does it reference any existing issues you know about? (include a link please)
* Any caveats, considerations or quid pro quos?

**Comment by SensibleWood** [comment]
@spacether please see the issue above I've opened up to investigate the failing build.

This is a prerequisite to amending your tooling data as your repository is correctly tagged with the topic `openapi31` and therefore will be flagged correctly once the build is fixed:

![image](https://github.com/OAI/Tooling/assets/2420069/3278f834-6aae-48fe-8a91-ff6c86935eff)

Please bear with me. I've not had time to investigate the build failures until this week.

**Comment by SensibleWood** [comment]
Build fixed due to issue with PAT as described in #97.

Data updated:

![image](https://github.com/OAI/Tooling/assets/2420069/2b33edce-05c9-4901-81c5-7067c2402f2e)

Closing this issue as a result.

**Comment by spacether** [comment]
Thanks!
